[deploy]
bucket = 'cfn-artifacts'
region = 'us-east-1'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:424925313933:certificate/a42282cc-81d2-424d-b8f1-cf7ddee4e185'
NetworkingStack = 'CrdNet'